name: 'GitHub Actions pull'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '33 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  elecV2P_pull:
    runs-on: ubuntu-latest
    steps:
      - name: set_time
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
      - name: "clone elecV2P"
        run: |
          rm -rf elecV2P
          git clone https://github.com/elecV2/elecV2P.git
          cd elecV2P 
          rm -rf .git 
          echo "=================="
      - name: "clone dust"
        run: |
          rm -rf dust
          git clone https://github.com/monk-coder/dust.git
          cd dust 
          rm -rf .git 
          echo "=================="
          cd ..
          echo "# 更新时间⌚️ 
          > $(date +%Y%m%d %H:%M)" > README.md          
      - name: Commit files
        run: |
          pwd
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +%Y%m%d-%H:%M)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
