name: HostUpdate

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '30 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.22.0
        
    - name: Run tasks
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python host/socket_query.py
        
    - name: Commit files
      run: |
        pwd
        ls
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Host" -a
    - name: 'Push changes'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
